CREATE SEQUENCE TB_REVIEWS_REVIEW_NO_SEQ
START WITH 1
INCREMENT BY 1
;
CREATE TABLE TB_REVIEWS (
    REVIEW_NO NUMBER DEFAULT TB_REVIEWS_REVIEW_NO_SEQ.NEXTVAL PRIMARY KEY, -- 리뷰 고유번호 (PK, 자동 증가)
    USER_ID VARCHAR2(20) NOT NULL, -- 작성자 ID (FK, TB_USERS 테이블 참조)
    TITLE NVARCHAR2(30) NOT NULL,  -- 리뷰 대상 콘텐츠 제목 (FK, TB_CONTENTS 테이블 참조)
    REVIEW_TEXT NVARCHAR2(2000),     -- 리뷰 본문
    RATING NUMBER(1) NOT NULL CHECK (RATING >= 1 AND RATING <= 5), -- 평점 (1~5점 사이)
    CREATED_AT DATE DEFAULT SYSDATE   -- 리뷰 작성 시점 (자동 기록)
);
COMMENT ON TABLE TB_REVIEWS IS '콘텐츠 리뷰 게시판';
COMMENT ON COLUMN TB_REVIEWS.REVIEW_NO IS '리뷰 고유 번호 (PK)';
COMMENT ON COLUMN TB_REVIEWS.USER_ID IS '작성자 ID (FK)';
COMMENT ON COLUMN TB_REVIEWS.TITLE IS '리뷰 대상 콘텐츠의 제목';
COMMENT ON COLUMN TB_REVIEWS.REVIEW_TEXT IS '리뷰 본문 내용';
COMMENT ON COLUMN TB_REVIEWS.RATING IS '1~5점 사이의 평점';
COMMENT ON COLUMN TB_REVIEWS.CREATED_AT IS '리뷰 작성 시점';
SELECT
      *
  FROM
      TB_REVIEWS;
COMMIT;
INSERT
  INTO 
        TB_REVIEWS
  VALUES(
    TB_REVIEWS_REVIEW_NO_SEQ.NEXTVAL
    	,'admin01'
       ,'케데헌'
       ,'아아아'
       , 3
       , SYSDATE 
);
SELECT
 	   *
  FROM 
       TB_CONTENTS 
  JOIN
  		TB_REVIEWS 
   USING
        (TITLE);
SELECT  
       *
  FROM   
       TB_REVIEWS
  JOIN
       TB_USERS
  USING 
        (USER_ID)
 WHERE
       USER_ID ='admin01';

SELECT * FROM TB_USERS;
        